### ISSUE TITLE
Enable LGTM

### ISSUE THREAD

**Issue by imincik** [linz/geospatial-data-lake#12]
With LGTM you can run security checks with tools like https://securitylab.github.com/tools/codeql. See what basemaps have done as an example: https://github.com/linz/basemaps/blob/master/.github/workflows/codeql-analysis.yml

**Comment by SPlanzer** [comment]
Codeql analysis has been implemented as per basemaps. 

@billgeo @imincik does this meet your expectations of ''Enable LGTM'?
