### ISSUE TITLE
Enable deploying test instance without conflicting with CI instance

### ISSUE THREAD

**Issue by l0b0** [linz/geospatial-data-lake#134]
Currently we have five elastic IPs, and each networking stack uses three. This means that if we deploy a test instance we break all CI pipelines, because they are unable to set up a networking stack. If we work around this by deploying a CI instance for testing purposes then any other CI pipelines will fail after waiting for two hours for the teardown of the existing stacks, which is not happening.

To resolve this we have a few options:

- Use fewer EIPs per networking stack. We should be able to use dynamic IPs for everything or almost everything.
- Pay for more EIPs. Probably not a good idea in the long run.
- Use a separate account for test instances. Probably not feasible, and also probably more expensive.

**Comment by imincik** [comment]
Good option is to use single AZ (with public IP address) if `DEPLOY_ENV` is not `prod`
