### ISSUE TITLE
HLD: remove Next Version information

### ISSUE THREAD

**Issue by imincik** [linz/geospatial-data-lake#227]
Remove Next Version information talking about implementation of web API. Primary reason is to keep focus only on MVP. All other iterations depend on our experience from MVP and it might be very premature to scope next versions now.

**Comment by imincik** [comment]
What do you think about this @billgeo ?

**Comment by billgeo** [comment]
Yes. I agree. We are at least 6-12 months away from considering this and it could be even longer, so fine to remove it and can retrieve from teh version history of the document later if needed.

**Comment by imincik** [comment]
Next Version removed from HLD
