### ISSUE TITLE
Bug: validate all files as collections

### ISSUE THREAD

**Issue by l0b0** [linz/geospatial-data-lake#254]
### Bug Description

We only want to support collection STAC files for now, so we should remove the catalog validation code.

**Comment by billgeo** [comment]
As discussed, I think we should enforce the best practice guide as described https://github.com/radiantearth/stac-spec/blob/master/best-practices.md and enforce STAC files to be named either `catalog.json`, `collection.json` or `<item_name>.json`.

**Comment by billgeo** [comment]
And also happy that we only accept collection.json files for the MVP.

**Comment by l0b0** [comment]
As far as I can tell we are already doing this. See https://github.com/linz/geospatial-data-lake/pull/284 for why we can't remove all reference to the catalog schema.
