### ISSUE TITLE
Improve S3 Batch copy of Dataset to handle larger amounts of files

### ISSUE THREAD

**Issue by MitchellPaff** [linz/geospatial-data-lake#260]
### Enabler
follow on  from https://github.com/linz/geospatial-data-lake-team/issues/69
S3 batch copy was implemented. To do this a csv manifest file is generated to specify every asset and metadata file to be copied.
It was decided that the MVP datasets are small enough to write the file in one go in the lambda. However if we were to support significantly larger datasets in the future, this csv file may become too large to write in one go.

So we may need to think about implementing [Batch Gets from the DynamoDB table ](https://pynamodb.readthedocs.io/en/latest/batch.html#batch-gets) and [creating a multipart upload to the s3 bucket ](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html#S3.Client.create_multipart_upload) in order to process all of the files without the processing Lambda running out of memory.

#### Acceptance Criteria
S3 Batch copy of Dataset into storage bucket works for very large datasets.

**Comment by billgeo** [comment]
Thanks @MitchellPaff.

**Comment by billgeo** [comment]
Resolved elsewhere
