### ISSUE TITLE
Bug: Nonprod role name changed

### ISSUE THREAD

**Issue by billgeo** [linz/geospatial-data-lake#316]
### Bug Description

Seems like the role name changed that I am trying to assume sometime in the last week or two.

It was: `nonprod-geospatial-data-lake-use-usersrole18D0AA3B-1GQ53EX8UMJC7`

Now it is: `nonprod-geospatial-data-lake-use-usersrole18D0AA3B-L1BSHG3ZPQJL`

I would assume they would be constant. Is the a suffix changed during deployment somehow?

#### Software and OS versions
 - OS: 
 - Environment: 
 - Relevant Software Versions:

**Comment by imincik** [comment]
Role name is fixed now. This wouldn't happen anymore.
