### ISSUE TITLE
Dataset Space: allow space deletion only if empty

### ISSUE THREAD

**Issue by imincik** [linz/geospatial-data-lake#43]
## User Story
So that I don't accidentally lose my important data, as Data Maintainer, I want to only delete datasets with no data in them.

Note: datasets can be altered in every way, so there should never be a need to delete them. We may implement an 'archive' feature later if needed.

## Accpetance Criteria
- Given a dataset with 1 or more versions, when a dataset DELETE is requested, then a message is returned and the dataset is not deleted
- Given a datasets with no versions created, when a dataset DELETE is requested, then the dataset is deleted and no longer appears in the list of datasets

## Tasks
- [ ]

## Ready
- [x] This story is ready

## Done
- [ ] This story is done.

**Comment by billgeo** [comment]
Rewrite as user story

**Comment by billgeo** [comment]
As discussed. This will be a problem, if we don't fix this I think.

**Comment by billgeo** [comment]
hi @l0b0 I get the error described in #567 when tryin to test this. Can you please have a look.
