### ISSUE TITLE
Bug: File copy does not strip original file prefix

### ISSUE THREAD

**Issue by l0b0** [linz/geospatial-data-lake#452]
### Bug Description

Currently S3 objects are copied into the storage bucket with the same prefix as the originals. That is s3://bucket-name/foo/bar/baz.json will end up at s3://storage-bucket/[dataset ID]/[version ID]/foo/bar/baz.json.

### How to Reproduce

1. Create a dataset within an S3 "folder" (prefix ending with a slash)
2. Import the dataset above

What happened? The result is that URLs like s3://bucket-name/foo/bar/baz.json end up at s3://storage-bucket/[dataset ID]/[version ID]/foo/bar/baz.json.

What should happen? URLs like s3://bucket-name/foo/bar/baz.json should end up at s3://storage-bucket/[dataset ID]/[version ID]/baz.json (note that the prefix is gone).

**Comment by billgeo** [comment]
Tested and seems to be working well. Thanks @l0b0
