### ISSUE TITLE
Make import status messages more meaningful

### ISSUE THREAD

**Issue by billgeo** [linz/geospatial-data-lake#539]
### User Story

So that I can quickly understand the status of my import, as a Data Maintainer, I want to clear and relevant import status messages.

This message:

```
{
  "statusCode": 200,
  "body": {
    "step function": {
      "status": "SUCCEEDED"
    },
    "validation": {
      "status": "Failed",
      "errors": [
        {
          "check": "checksum",
          "result": "Failed",
          "url": "s3://xxxxxx/data_lake_test/checksum_validation_fails/empty_file.tif",
          "details": {
            "message": "Checksum mismatch: expected e3bcc44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855, got e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
          }
        }
      ]
    },
    "metadata upload": {
      "status": "Pending",
      "errors": []
    },
    "asset upload": {
      "status": "Pending",
      "errors": []
    }
  }
}
```

Would be more meaningful it it was something like this:

```
{
  "statusCode": 200,
  "body": {
    "step function": {
      "status": "Completed"        <-- Lower case and 'Completed' rathe than 'Suceeded' 
    },
    "validation": {
      "status": "Failed",
      "errors": [
        {
          "check": "checksum",
          "result": "Failed",
          "url": "s3://xxxxxx/data_lake_test/checksum_validation_fails/empty_file.tif",
          "details": {
            "message": "Checksum mismatch: expected e3bcc44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855, got e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
          }
        }
      ]
    },
    "metadata upload": {
      "status": "Cancelled",       <-- "Cancelled" instead of "Pending"
      "errors": []
    },
    "asset upload": {
      "status": "Cancelled",      <-- "Cancelled" instead of "Pending"
      "errors": []
    }
  }
}
```

#### Acceptance Criteria

- [ ] Given [a pre-condition], when [an event happens], then [an expected outcome occurs]
- [ ] Given [a pre-condition], when [an event happens], then [an expected outcome occurs]

#### Tasks

- [ ] ...
- [ ] ...

#### Definition of Ready
- [ ] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [ ] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

**Comment by l0b0** [comment]
"SUCCEEDED" is the literal value the AWS API reports. We can easily lowercase or Title-Case it. As for changing it to "completed", that is less informative, since it doesn't say whether the stage was successful.

"Cancelled" instead of "Pending" - completely agree; we need to be able to distinguish them.

**Comment by billgeo** [comment]
There's also this one which seems to have a few isssues:

```
{
  "statusCode": 200,
  "body": {
    "step function": {
      "status": "FAILED"                 <-- Why not 'SUCCEEDED', like the one above?
    },
    "validation": {
      "status": "Pending",                <-- Should be 'Failed'?
      "errors": [
        {
          "check": "JSON schema",
          "result": "Failed",
          "url": "s3://data-lake-test-bn/data_lake_test/tasman_invalid_metadata/collection.json",
          "details": {
            "message": "'' does not match '^[\\\\w\\\\-\\\\.\\\\+]+$'\n\nFailed validating 'pattern' in schema['allOf'][1]['properties']['license']:\n    {'pattern': '^[\\\\w\\\\-\\\\.\\\\+]+$',\n     'title': 'Collection License Name',\n     'type': 'string'}\n\nOn instance['license']:\n    ''"
          }
        }
      ]
    },
    "metadata upload": {
      "status": "Pending",            <-- Again, 'Cancelled'?
      "errors": []
    },
    "asset upload": {
      "status": "Pending",         <-- Again, 'Cancelled'?
      "errors": []
    }
  }
}
```

**Comment by billgeo** [comment]
> "SUCCEEDED" is the literal value the AWS API reports. We can easily lowercase or Title-Case it. As for changing it to "completed", that is less informative, since it doesn't say whether the stage was successful.

Okay, thanks. I didn't realise the STEP Function can be 'SUCCEEDED' while data copying processes are still happening. Can probably leave that bit for now then, until we have a proper API etc.
