### ISSUE TITLE
Lambda bundling script is installing much more packages than required

### ISSUE THREAD

**Issue by imincik** [linz/geospatial-data-lake#62]
Lambda bundling script is installing much more packages than required by `requirements.txt` file. Lambda runtime contains lot of pre-installed packages and only those mentioned in `requirements.txt` file needs to be bundled with our Python function.

**Comment by l0b0** [comment]
I think there are two separate issues here:

1. The checked-in requirements.txt files only contain the top-level dependencies. I'll fix that to include the tree of dependencies and some instructions for updating the requirements.txt files.
1. The CDK asset directories do not contain any unnecessary packages as far as I can see - only the packages in the relevant `endpoint/*/requirements.txt` file (and their dependencies, as mentioned above) are part of each Lambda function bundle.

**Comment by imincik** [comment]
This is not a problem anymore.
