### ISSUE TITLE
Bug: CloudFormation export can't be updated as it is in use by other stack

### ISSUE THREAD

**Issue by imincik** [linz/geospatial-data-lake#630]
When passing resources between stacks (for example like [here](https://github.com/linz/geospatial-data-lake/blob/master/app.py#L55) ) , CDK is using Exports to pass this information between stacks on CloudFormation level.

Example of Exports in `storage` stack CloudFormation template:
```
  "Outputs": {
    "ExportsOutputFnGetAttstoragebucket3510E1B1ArnA44443B2": {
      "Value": {
        "Fn::GetAtt": [
          "storagebucket3510E1B1",
          "Arn"
        ]
      },
      "Export": {
        "Name": "nonprod-geospatial-data-lake-storage:ExportsOutputFnGetAttstoragebucket3510E1B1ArnA44443B2"
      }
    },
    "ExportsOutputRefstoragebucketname03BA64D6B71F9B12": {
      "Value": {
        "Ref": "storagebucketname03BA64D6"
      },
      "Export": {
        "Name": "nonprod-geospatial-data-lake-storage:ExportsOutputRefstoragebucketname03BA64D6B71F9B12"
      }
    },
```

This results in following stack upgrade errors when resources are moved between stacks and Exports need to be removed from stack:

```
 10/11 | 5:31:34 AM | UPDATE_ROLLBACK_IN_P | AWS::CloudFormation::Stack | ci787925127-geospatial-data-lake-storage Export ci787925127-geospatial-data-lake-storage:ExportsOutputRefci787925127datasetsci787925127datasetstablenameforci787925127B9979E3F131A4311 cannot be updated as it is in use by ci787925127-geospatial-data-lake-api
```

Relevant CDK issue: https://github.com/aws/aws-cdk/issues/5304

Nice problem description and solution: https://aws-blog.de/2020/09/deployment-issues-with-cross-stack-dependencies-and-the-cdk.html

## How to Reproduce

1. Do …
1. Run `…`

What did you expect to happen? 

What actually happened? 

## Software Context

Operating system: 

Environment: 

Relevant software versions:

- AWS CLI: 
- Poetry:

**Comment by billgeo** [comment]
Will try out nested stacks and see if that works

**Comment by imincik** [comment]
@l0b0 , [here] is nice problem description and solution which we can use in case we need to manipulate resources which will require CloudFormation Exports to be changed (which leads to our problem).

**Comment by imincik** [comment]
@l0b0 , here is some example of building nested stacks which after first looks can work for us as well

https://github.com/ryands17/cdk-nested-stacks/blob/main/lib/nested-stacks.ts
