### ISSUE TITLE
Infra: slow launch of AWS Batch containers

### ISSUE THREAD

**Issue by imincik** [linz/geospatial-data-lake#81]
There is a significant latency (more than 10 seconds) in AWS Batch containers launch for each new container in array. 

ECS agent is configured to cache Docker images by following configuration, but it might not work correctly.

```
ECS_IMAGE_PULL_BEHAVIOR=prefer-cached >> /etc/ecs/ecs.config
``` 

More investigation is needed. Requires ssh to ECS instance.

**Comment by billgeo** [comment]
Already fixed as well as we can
